# Generated by Django 3.0.3 on 2020-02-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('raw_html', models.TextField(blank=True, null=True, verbose_name='Raw html')),
                ('page_name', models.CharField(max_length=100, verbose_name='Page name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('raw_html', models.TextField(blank=True, null=True, verbose_name='Raw html')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_seo', to='blog.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
