# Generated by Django 3.0.3 on 2020-02-07 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('created', ckeditor.fields.RichTextField(verbose_name='Body')),
            ],
        ),
    ]
