# Generated by Django 3.0.3 on 2020-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200207_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='post_images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
