# Generated by Django 3.0.3 on 2020-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='subtagline',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Subtagline'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tagline'),
        ),
    ]
