# Generated by Django 3.0.3 on 2020-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_faquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='category_logos/', verbose_name='Logo')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Parsing category',
                'verbose_name_plural': 'Parsing categories',
            },
        ),
    ]
