# Generated by Django 3.0.3 on 2020-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_parsingcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='examples_header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Examples header'),
        ),
    ]
