# Generated by Django 3.0.3 on 2020-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='about_us_list',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=250, null=True, verbose_name='About us list'),
        ),
    ]
