# Generated by Django 3.0.3 on 2020-02-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_indexpage_about_us_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
    ]
