# Generated by Django 3.0.3 on 2020-02-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200207_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examples',
            new_name='Example',
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Index page', 'verbose_name_plural': 'Index page'},
        ),
    ]
