# Generated by Django 3.0.3 on 2020-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200207_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Example', 'verbose_name_plural': 'Examples'},
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='example',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='examples/', verbose_name='File'),
        ),
    ]
