# Generated by Django 3.0.3 on 2020-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200207_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
    ]
