# Generated by Django 3.0.3 on 2020-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_indexpage_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='short_about',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Short about'),
        ),
    ]
