# Generated by Django 3.0.3 on 2020-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_indexpage_short_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
